image: docker:latest

services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
    - elixir_build_tests

elixir_build_tests:
  stage: elixir_build_tests
  before_script:
    - apk add build-base
    - apk add python3-dev
    - apk add libffi-dev
    - apk add openssl-dev
    - apk add --no-cache py-pip
    - apk add rust
    - apk add cargo
    - pip install docker-compose==1.27.4
  script:
    - pwd
    - docker-compose -p solution up -d
    - docker ps
    - sleep 10
    - docker ps
    - echo "Forcing deps gets to workaround CI issues for now"
    - docker exec api bash -c "mix deps.get"
    - docker exec api bash -c "mix deps.update telemetry"
    - echo "Executing tests..."
    - make test
